### ISSUE TITLE
Keksrotz entfernen

### ISSUE THREAD

**Issue by L3P3** [odincat/DefaultWebTheme#1]
Die Seite verwendet garkeine Cookies und für eine "einfache" Seite ist das auch garnicht notwendig. Außerdem nerven solche Popups extrem.

Referenz: https://l3p3.de/

Keep it simple, Cat!

**Comment by odincat** [comment]
Danke für deinen Input! Ich habe ihn jetzt erstmal removed, eben weil es ja momentan noch keine Cookies gibt. Irgendwann später werde ich vielleicht nochmal Cookies verwenden, dann werde ich mir nochmal eine bessere Lösung als irgend so ein fertiges, sperriges Ding.
